# docker-compose.yml
version: '2'

services:
  db:
    image: mysql:5.6
    ports:
    - 3306:3306
    volumes:
    - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: yourpass
  php:
    build: Docker/phpfpm
    ports:
    - 9000:9000
    links:
    - db:mysqldb
    volumes:
    - ./:/var/www/symfony
    - ./logs/symfony:/var/www/symfony/app/logs
  nginx:
    build: Docker/nginx
    ports:
    - 80:80
    links:
    - php
    volumes_from:
    - php
    volumes:
    - ./logs/nginx/:/var/log/nginx
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    links:
    - db